version: "1.0"

services:
  service-db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    restart:
      always
    volumes:
      - db_volume:/var/lib/postgresql/data

  service-app:
    build: .
    env_file:
      - ./.env
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - service-db
  
volumes:
  db_volume: